name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
    - name: Build and run Docker Compose
      run: |
        docker compose up -d
    - name: Test
      run: |
        curl --retry 10 --retry-connrefused [invalid url, do not cite]
    - name: Clean up
      run: |
        docker compose down